### ISSUE TITLE
Add in jackknife standard errors for gee estimates

### ISSUE THREAD

**Issue by svteichman** [statdivlab/raoBust#11]
Code was graciously provided in [this issue we opened for `geeasy`](https://github.com/annennenne/geeasy/issues/4#issuecomment-2081876280) as an easy way to add jackknife standard errors to the gee estimates that we get from the `geeasy` package. 

To-do: implement these and check that they give similar results to the jackknife standard errors in `geepack` (when `geepack` converges that is; we use `geeasy` instead of `geepack` in `raoBust` because of instances in which the call to `geepack` has caused code hanging without hitting an error). 

```
get_jack_se <- function(object, dat){
    parm <- sapply(1:nrow(dat),
                   function(i){
                       dat.i <- dat[-i,]
                       coef(update(object, data=dat.i))
                   })
    parm <- t(parm)
    parm.mean <- apply(parm, 2, mean)
    
    parm.cent <- sapply(1:nrow(parm),
                        function(i){
                            parm[i, ] - parm.mean
                        })
    parm.cent <- t(parm.cent) 
    
    jack.var <- ((nrow(dat)-1) / nrow(dat)) * t(parm.cent) %*% parm.cent
    jack.se <- sqrt(diag(jack.var))
    jack.se
}


# EXAMPLE
data("respiratory")
respiratory$useid <- interaction(respiratory$center, respiratory$id)

# fit model
obj <- geelm(outcome ~ treat + sex + age + baseline, 
           data = respiratory, id = useid,
                      family = "binomial", corstr = "exchangeable")

dat <- respiratory
get_jack_se(obj, dat)
# compare with
summary(m) |> coef()
```

**Comment by svteichman** [comment]
Closing because this is implemented in PR #13

**Comment by svteichman** [comment]
@hojsgaard We really appreciate your thoughts [from this issue](https://github.com/annennenne/geeasy/issues/4) and have implemented a cluster adapted version of the code in your comment in our package `raoBust`. We would like to add you as a contributor in the authors field of our DESCRIPTION file to acknowledge this assistance, with your permission.

**Comment by hojsgaard** [comment]
You are more than welcome.
Best
Søren

-----Original Message-----
From: Sarah Teichman ***@***.******@***.***%3e>>
Reply-To: statdivlab/raoBust ***@***.******@***.***%3e>>
To: statdivlab/raoBust ***@***.******@***.***%3e>>
Cc: Søren Højsgaard ***@***.******@***.***%3e>>, Mention ***@***.******@***.***%3e>>
Subject: Re: [statdivlab/raoBust] Add in jackknife standard errors for gee estimates (Issue #11)
Date: 06/06/2024 08:47:06 PM


@hojsgaard<https://github.com/hojsgaard> We really appreciate your thoughts from this issue<https://github.com/annennenne/geeasy/issues/4> and have implemented a cluster adapted version of the code in your comment in our package raoBust. We would like to add you as a contributor in the authors field of our DESCRIPTION file to acknowledge this assistance, with your permission.
