### ISSUE TITLE
Questions regarding multinomial test

### ISSUE THREAD

**Issue by Ge0rges** [statdivlab/raoBust#21]
Hi @svteichman 

I was wondering if you could help me understand a few points about the multinomial test.

- Can I run the strong test with only two covariates (i.e. 2 columns in X) to understand whether they are different to each other?
- Currently, my Y matrix represents replicate observations when the covariate is identical. For example, all rows in Y represent observations in different samples (covariates, indicates by X) of the same nucleotide in a genome. However, let's say I want to know if two genes are different by the collection of nucleotides that compose them. My intuition would be to essentially produce a Y and X for the gene that would be the vertically stacked concatenation of Y,X for each nucleotide (i.e., let's say a nucleotide Y matrix is 4*9, and a gene is 10 nucleotides I would have a 40*9 shape). Does this make sense?
- As a follow up to the above question, if I want to preserve the position information of the nucleotide within the gene, does this test accomplish that? (i.e., the order of the rows in Y and X matters).

Thanks for your help.

**Comment by svteichman** [comment]
Hi @Ge0rges, great questions.

- You can run the strong test with only 2 columns in X, any number of covariates can be used here. 
- I'm going to think through this question a little more (I don't have an immediate answer) but I'll get back to you on this! 
- The ordering of `Y` and `X` are arbitrary, so I think it wouldn't preserve the position information of the nucleotides within the gene.

**Comment by Ge0rges** [comment]
Thanks for that @svteichman. Is there a version of the test that preserves position information?

**Comment by svteichman** [comment]
My instinct is no, but I'll need to think about this further. I'm out of the office right now, but will get back to you on these questions later in the week!

**Comment by svteichman** [comment]
Hi @Ge0rges, 

I'm somewhat confused about your question above:

"Currently, my Y matrix represents replicate observations when the covariate is identical. For example, all rows in Y represent observations in different samples (covariates, indicates by X) of the same nucleotide in a genome. However, let's say I want to know if two genes are different by the collection of nucleotides that compose them. My intuition would be to essentially produce a Y and X for the gene that would be the vertically stacked concatenation of Y,X for each nucleotide (i.e., let's say a nucleotide Y matrix is 49, and a gene is 10 nucleotides I would have a 409 shape). Does this make sense?"

When you saw that all rows in Y represent observations in different samples of the same nucleotide in a genome, what exactly do you mean? The way that I think about Y in this model is a matrix with n rows and J columns, in which a row is a vector of length J. So row 1 corresponds to sample 1, and Y_[row 1, column 1] represents the count of category 1 in sample 1 and Y_[row 1, column J] represents the count of category J in sample 1. If your categories here are nucleotides, then a row would correspond to the counts for all nucleotides for a specific sample, and a column would correspond to counts for a specific nucleotide for all samples. 

If this all makes sense, then I think it would make sense to make a Y that concatenates your nucleotides. This Y, instead of being size n x 49 for a single nucleotide, would be n x 490 if each gene is made up of 10 nucleotides, which each have 10 columns. 

One follow-up question that I have is what the counts in Y represent. What does Y_[sample 1, nucleotide position 1] represent? 

As far as preserving the positional information of nucleotides in your gene, this test will not do that. The ordering of the columns of Y does not have an affect on the result, or on the interpretation of this test.

**Comment by Ge0rges** [comment]
> If your categories here are positions in nucleotides, then a row would correspond to the counts for all nucleotide positions for a specific sample, and a column would correspond to counts for a specific nucleotide position for all samples.


> If this all makes sense, then I think it would make sense to make a Y that concatenates your nucleotides. This Y, instead of being size n x 49 for a single nucleotide, would be n x 490 if each gene is made up of 10 nucleotides, which each have 10 positions
> 
> One follow-up question that I have is what the counts in Y represent. What does Y_[sample 1, nucleotide position 1] represent?

Here my categories are different features (methylation types) of each nucleotide. So currently my Y represents information about one nucleotide where each row is a sample (indicated in X), and each column is a methylation type, and a value at a given row/column combo is the number of times that methylation type was observed in that sample for the nucleotide represented by this entire Y matrix. 

So it sounds like we are on the same page and I can concatenate multiple Y's together to test a gene.

> As far as preserving the positional information of nucleotides in your gene, this test will not do that. The ordering of the columns of Y does not have an affect on the result, or on the interpretation of this test.

I guess this is perhaps an issue for once we get this first test sorted, but I am curious if there is a test that would be similar to this one while additionally taking into account the positional information.

Thanks for all your help.

**Comment by Ge0rges** [comment]
Hi @svteichman,

Another question came up on my end. I was wondering if there is a way to get effect size from this test?

**Comment by svteichman** [comment]
I'm not sure if this is what you're interested in, but you can get estimates of the parameters using the multinomial model. If you look at the output and look at the object `mle1`, this gives the $\beta$ vector under the alternative hypothesis. The value of $\beta$ for the second row and first column represents the expected log fold change in the count of the nucleotide position represented by the first column of $Y$ between the levels of your covariate, relative to the expected log fold change relative to the covariate for the nucleotide position represented by the $J$th column of $Y$. The more this is different than $0$, the larger the effect of the covariate on the count of the first column of $Y$.

**Comment by svteichman** [comment]
However, because both the weak null and strong null require testing combinations of parameters, there is currently no way to combine these estimates to get a single effect size for a test.

**Comment by Ge0rges** [comment]
Would it be suitable to use those values to rank different comparisons then by effect size?

**Comment by Ge0rges** [comment]
Hi @svteichman, I noticed that in the returned object by the test I get:
```
o{'test_stat': [166.33678665], 'p': [2.69001739e-33], 'mle0': [[-4.1515383  -5.08389535 -6.15250986]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]], 'mle1': [[-2.78884508 -3.5049136  -5.82517578]
 [-1.21725714 -1.2632907   0.20980623]
 [-1.59158794 -2.2616229  -6.05498201]], 'penalty': [1] FALSE
, }
```
What does `test_stat` correspond to, and could that be used as a rank?

**Comment by svteichman** [comment]
`test_stat` is the robust score test statistic, which quantifies how much evidence we have against the null hypothesis from this data. In this case, it could be used to rank tests in terms of which ones have the most evidence against the null (with larger values providing more evidence). You could also use the p-values, there will be a monotonic relationship between the test statistic and p-value, if one test has a larger test statistic than another, it will also have a smaller p-value than the other.

**Comment by Ge0rges** [comment]
@svteichman one (hopefully) last question for you. Would this test handle cases where there are an unequal number of replicate per covariate? E.g. total number of rows in X is 5, there are 3 rows where the first covariate is 1, and the last 2 are for a second covariate. Or must I ensure that the replicate number if equal for each covariate (this becomes important when I move from nucleotides to genes as not all nucleotides in a gene were sampled equally, some were sample once, twice, and others there times). Thanks.

**Comment by svteichman** [comment]
There is no need to have balanced groups for this method, which is how I'm interpreting your question. You can have any number of observations for each level or value of the covariate that you're working with.

**Comment by Ge0rges** [comment]
Perhaps this comes down to the same mathematically (or it is what you mean), but my intent is to understand if having different number of rows in Y for each covariate matters rather, than discussing the value at any given position in Y.

**Comment by adw96** [comment]
Nope that's fine, Gio.

**Comment by Ge0rges** [comment]
Hey all, this seems a little ridiculous to ask but I wanted to double check. When the function returns a significant p value, that means that the items compared (assuming strong hypothesis) are all the same, correct? And under the weak at j, a significant p value means the items compared are all the same as j?

So I can't say when the p value is insignificant that under the strong all the items are the same, correct?

**Comment by svteichman** [comment]
The strong null hypothesis is that the parameters for all non-intercept coefficients is equal to zero. Therefore, a significant p-value allows you to reject the null hypothesis, and conclude that for at least one category and one covariate or covariate level, there is a non-zero expected log fold difference in the abundance of that category with respect to a change in that covariate. 

The weak null hypothesis for category j is that all non-intercept parameters related to category j are equal to 0. Therefore, a significant p-value allows you to reject the null hypothesis, and conclude that for at least one covariate or covariate level, there is a non-zero expected log fold difference in the abundance of category j with respect to a change in that covariate. 

I'm not sure what you mean by saying that all items are the same, so I'm not sure how that fits into the strong or weak hypothesis. When a p-value is insignificant it means that you don't have enough evidence to reject the null, but you cannot conclude that the null is true, as it's possible that you just don't have the power to detect a true difference.

**Comment by Ge0rges** [comment]
I was wondering if the counts in the Y matrix should be normalized in any way?

**Comment by svteichman** [comment]
No need for normalization, the benefit of using a multinomial model is that you condition on the total counts from each sample, which accounts for differences in total magnitudes between samples (which is what normalization tends to account for).
